services:
  postgres_db:
    image: postgres:latest
    container_name: news_rssFeed_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: news_db
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news_rssFeed_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sh:/app/init.sh
    ports:
      - "5432:5432"
    command: ["/bin/bash", "-c", "docker-entrypoint.sh postgres & sleep 10 && /app/init.sh && wait"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "news_db", "-d", "news_rssFeed_db", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  rss_scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rss_scraper
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      rss_feed_url: "https://www.thehindu.com/news/national/?service=rss"
      title: "title"
      summary: "summary"
      article_link: "link"
      tags: "tags"
      image_url: "media_content"
      pub_timestamp: "published"
      DB_HOST: "postgres_db"
      DB_PORT: "5432"
      DB_NAME: "news_rssFeed_db"
      DB_USER: "news_db"
      DB_PASSWORD: "password"
      POLLING_INTERVAL: "600"
    command: ["sh", "-c", "sleep 5 && python scraper.py"]
  
volumes:
  postgres_data:
